PasswordProject/BasicApp/urls.py
from django.urls import path
from BasicApp import views

app_name = 'BasicApp'

urlpatterns = [
path('registration/', views.registration, name = 'registration'),
path('login/', views.user_login, name = 'login')
]

PasswordProject/PasswordProject/urls.py
from django.contrib import admin
from django.urls import path, include
from BasicApp import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    path('BasicApp/', include('BasicApp.urls')),
    path('logout/', views.user_logout, name = 'logout'),
]

PasswordProject/BasicApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,)

    portfolio = models.URLField(blank = True)
    picture = models.ImageField(upload_to='profile_pics', blank = True)

    def str(self):
        return self.user.username

PasswordProject/BasicApp/forms.py
from django import forms
from BasicApp.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)

    class Meta():
        model = User
        fields =['username', 'email', 'password']

class UserProfileInfoForm(forms.ModelForm):


    class Meta():
        model = UserProfileInfo
        fields = ['portfolio', 'picture']

PasswordProject/BasicApp/views.py
from django.shortcuts import render
from BasicApp.forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
# Create your views here.
def index(request):
    return render(request, 'BasicApp/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def registration(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user



            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True

        else:

            print(user_form.errors, profile_form.errors)
    else:
            user_form = UserForm()
            profile_form = UserProfileInfoForm

    return render(request, 'BasicApp/registration.html',
                             {'registered': registered,
                             "user_form": user_form,
                             "profile_form": profile_form})






def user_login(request):


    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password = password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                print("could not login")
                return HttpResponse('Account not active')

        else:
            return HttpResponse("Invalid login details supplied")


    else:
        return render(request, 'BasicApp/login.html', {})

PasswordProject/templates/BasicApp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <title></title>

  </head>
  <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">Django</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
            <a class="nav-link active" aria-current="page" href="{% url 'BasicApp:registration' %}">Register</a></li>
            {% if user.is_authenticated %}
            <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Log Out</a></li>

            {% else %}
<a class="nav-link active" aria-current="page" href="{% url 'BasicApp:login' %}">Log In</a></li>
{% endif %}
          </div>
        </div>
      </div>
    </nav>




<div class="container">
  {% block body_block %}
  {%  endblock%}
</div>


  </body>
</html>

PasswordProject/templates/BasicApp/index.html
<!DOCTYPE html>
{% extends "BasicApp/base.html" %}

{% block body_block %}

<div class="bg-light m-2 p-5 rounded ">
<h1>Django INDEX PAGE</h1>
</div>
{% endblock %}

PasswordProject/templates/BasicApp/login.html
<!DOCTYPE html>
{% extends "BasicApp/base.html" %}

{% block body_block %}

<div class="bg-light m-2 p-5 rounded ">

<h1>Please Login</h1>

<form action="{% url 'BasicApp:login' %}" method="post">
{% csrf_token %}

<label for="username">Username</label>
<input type="text" name="username" placeholder="Enter username">
<label for="password"></label>
<input type="password" name="password" >
<input type="submit" name="" value="Login">
</form>

</div>

{% endblock %}

PasswordProject/templates/BasicApp/registration.html
<!DOCTYPE html>
{% extends "BasicApp/base.html" %}
{% load static %}


{% block body_block %}

<div class="bg-light m-2 p-5 rounded ">
{% if registered %}
<h1>Thank you for registerin</h1>

{% else %}
<h1>Register Here</h1>
<h3>Fill out the form</h3>

<form enctype="multipart/form-data" method="post">
{% csrf_token %}
{{ user_form.as_p }}
{{ profile_form.as_p }}
<input type="submit" name="" value="Register">

</form>

{% endif %}
</div>
{%endblock%}